### ISSUE TITLE
I want 3 values for IsMinor ie. Yes, No, Lab

### ISSUE THREAD

**Issue by Siddiq200** [GoodDeeds/Timetabler#5]
I want 3 values for IsMinor ie. Yes, No, Lab ? Can you give me some guidence for this ?

I have changed 

Minor.h:

```
enum MinorType {
	/**
	 * Value when the Course is a minor course
	 */
    isMinorCourse,
    /**
     * Value when the Course is not a minor course
     */
    isNotMinorCourse,
    /**
     * Value when the Course is not a minor course
     */
    isLabCourse
};
```

Parsing Input:

```
std::string isMinorStr = parser[i]["is_minor"];
        int isMinor;
        if (isMinorStr == "Yes") {
            isMinor = 0;
            assignmentsThisCourse[FieldType::isMinor].push_back(l_True);
        } else if (isMinorStr == "No") {
            isMinor = 1;
            assignmentsThisCourse[FieldType::isMinor].push_back(l_False);
        } else if(isMinorStr == "Lab"){
            isMinor = 2;
            assignmentsThisCourse[FieldType::isMinor].push_back(l_False);
        }else{
            std::cout << "Input contains invalid IsMinor value (should be 'Yes' , 'No' or 'Lab')" << std::endl;
            exit(1);
        }
```

Parsing YML:

```
 IsMinor isMinor = MinorType::isNotMinorCourse;
        std::string isMinorString = slotNode["is_minor"].as<std::string>();
        if(isMinorString == "true"){
            isMinor = MinorType::isMinorCourse;
        }else if(isMinorString == "false") {
            isMinor = MinorType::isNotMinorCourse;
        }else if(isMinorString == "lab"){
            isMinor = MinorType::isLabCourse;
        }
```
Parser line 67:

```
timeTabler->data.isMinors.push_back(IsMinor(MinorType::isMinorCourse));
    timeTabler->data.isMinors.push_back(IsMinor(MinorType::isNotMinorCourse));
    timeTabler->data.isMinors.push_back(IsMinor(MinorType::isLabCourse));
```
ConstraintAdder:

```
Clauses ConstraintAdder::minorInMinorTime() {
    Clauses result;
    result.clear();
    std::vector<Course> courses = timeTabler->data.courses;
    for(int i = 0; i < courses.size(); i++) {
        /*
         * a minor course must be in a minor Slot.
         * a non-minor course must not be in a minor Slot.
         */
        if(courses[i].getIsMinor() == 2){
            Clauses antecedent1 = encoder->isLabCourse(i);
            Clauses consequent1 = encoder->slotInLabTime(i);
            result.addClauses(antecedent1>>consequent1);
            result.addClauses(consequent1>>antecedent1);
        }else{
            Clauses antecedent = encoder->isMinorCourse(i);
            Clauses consequent = encoder->slotInMinorTime(i);
            result.addClauses(antecedent>>consequent);
            result.addClauses(consequent>>antecedent);}

    }
    return result;
}


```Please Guide me what else should I do.

**Comment by Siddiq200** [comment]
assignmentsThisCourse[FieldType::isMinor].push_back(l_False);
I did not understand this line ? 

I have worked on Java I am New to C++ and OpenWBO

**Comment by GoodDeeds** [comment]
Changes:
* is_minor.h
  Your changes are fine. You may need to remove or properly handle the constructor which accepts a `bool` so that it behaves as you expect, as your case has three possible values.
* parser.cpp
  `assignmentsThisCourse[FieldType::isMinor].push_back(l_False);` means that a variable in the solver to specify whether the course is minor is assigned to false. Since the original code has it as a boolean value, a single variable was sufficient. In your case, if you want three values, you could replace it with two variables, as in the [program example](https://github.com/GoodDeeds/Timetabler/blob/master/src/parser.cpp#L166-L183)). Other changes in the parser are fine.
* constraint_adder.cpp 
  The change made will work, depending on the intention. Your change enforces exactly one out of the two, a lab course to be in lab time and minor course to be in minor time. If you then set your weights such that the solver can change this field for the course, then you may face unexpected behaviour. For example, if you set in the initial assignment that the course is to be a lab course, but allow the solver to change it to a minor course, the constraints on minor courses are not enforced. Similarly, if you do not provide any assignment at all, and let the solver choose one, and it chooses lab, the lab constraints will not be enforced. To avoid this, you just need to remove the if-else and add both constraints. I assume you have defined `isLabCourse()` and `slotInLabTime()` similar to the existing functions for minor.
  
The above should probably be sufficient. If Lab and Minor are independent of each other (i.e., if a course can be both), you could alternatively add a new field for `is_lab`, and copy code from `is_minor`.

**Comment by Siddiq200** [comment]
With the Above changes, adding two variables as you suggested in point 2 worked for me.... Thanks a lot.

As you mention in 3rd point I Remove If-Else to avoid any unexpected behaviour.

As you assume I have already defined `isLabCourse()` and `slotInLabTime()` similar to the existing functions for minor.

Now I can use 3 values for isMinor :)

Thanks for making Repository public.
Thanks for Help.
